### ISSUE TITLE
What is the protocoll for consecutive requests?

### ISSUE THREAD

**Issue by CexyChris** [IBM/zOS-Client-Web-Enablement-Toolkit#18]
So I tried to send the same request for 50.000 times but at roundabout 40.000 requests I get am abend saying 

> +IDI0002I Module HWTHMLPA offset X'B7B6': Abend S01F-X'4' 

which then results in a S0C4 with Reason Code 11, so a page translation exception.
What I did was (just like in the example):
1) Initialize connection
2) Setup connection
3) Connect to server
4) Initialize Request
5) Setup Request
6) Send Request in a PERFORM 50.000 TIMES - Loop
Step 7) would have been to terminate the request, then in 8) Disconnect and finally 9) Terminate the Connection, but I do not get there...

Are you able to reproduce this situation with similar results?
I work on z/OS V2R2.

Looking forward hearing from you!

**Comment by gorelikg** [comment]
The overview of the service calls looks correct, would you please open up a case record/PMR with IBM to further investigate the issue.  In the case record, please include the name of the sample you modified.
