### ISSUE TITLE
Slack only supports TLS 1.2 and later

### ISSUE THREAD

**Issue by ian-burnett** [IBM/zOS-Client-Web-Enablement-Toolkit#20]
As of March 4, 2020 Slack only supports TLS 1.2: https://api.slack.com/changelog/2019-07-deprecate-early-tls-versions

The z/OS CWET does not use TLS 1.2 by default. Need to change the sample in order to access Slack.

**Comment by gorelikg** [comment]
NOTE:
z/OS CWET does not have it's own default, when HWTH_OPT_SSLVERSION is used for the HWTH_OPT_SSLVERSION option, it translates into asking z/OS System SSL to use whatever default was defined for it on the system.  In short, z/OS CWET has no default, we just pass that ‘use default’ setting onto z/OS System SSL.
