### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sunil390** [IBM/zOS-Client-Web-Enablement-Toolkit#29]
Is there a plan to develop an example to post a message to Microsoft Teams Channel using webhook like the Slack example?

**Comment by sunil390** [comment]
The Slack example did work for Teams out of the box with one major issue.

The curly brackets are e2a translated to symbol : and hence getting a HTTP 400 return code. Now continuing with the research to fix this issue.

 /* Build the request body */
    requestData = '{' || ,
     '"channel":"'    || channelName   || '",' || ,
     '"username":"'   || userName      || '",' || ,
     '"text":"'       || textToDisplay || '"'  || ,
     '}'

**Comment by gorelikg** [comment]
Hi Sunil, 
I'm not aware of any plans for a similar example targeting Microsoft Teams Channel.

Hi Ian, (@ian-burnett )
Any chance you have something you're working on that would satisfy that request?

**Comment by ian-burnett** [comment]
I don't have access to a Microsoft Teams environment that will allow me to develop a sample.

Reading the Microsoft Teams documentation, however, gets me to the following pages: [Post external requests to Teams with incoming webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) and [Setting up a custom incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook).

It appears that messages can be posted to Teams using a standard HTTP POST operation - this is the same mechanism used by the Slack web API as demonstrated in the sample.

It should be a reasonably straightforward exercise to start from the Slack sample, change the URL, the message body, and import the correct SSL certificates into the SAF keyring / key database file.

Once you have a basic hello world working, then the documentation suggests that it's simply a matter of changing the HTTP POST payload to achieve various card functions.

If someone knows how I can get hold of a zero-cost Teams environment that will allow incoming webhooks, then I'm certainly open to putting together a sample.

**Comment by sunil390** [comment]
Thank You! Galena and Ian, I could make progress in connecting to teams. Will post the details here this weekend.

**Comment by blairwyman** [comment]
Sunil, so glad you could make progress.  Did you have good luck?

**Comment by sunil390** [comment]
[zAlert.zip](https://github.com/IBM/zOS-Client-Web-Enablement-Toolkit/files/6872809/zAlert.zip)
Greetings Blair,  I made very little changes to Ian's code as attached and it worked.

**Comment by sunil390** [comment]
MS Teams Integration worked as per Ian's suggestion. This request can be closed.

**Comment by ian-burnett** [comment]
Thanks for the update @sunil390 - very useful.
