### ISSUE TITLE
Getting HWTH-COMMUNICATION-ERROR 

### ISSUE THREAD

**Issue by arunk-81** [IBM/zOS-Client-Web-Enablement-Toolkit#35]
Hi Team,

I am trying to test the HTTP Web Enablement toolkit using the COBOL sample program (HWTHXCB1) for invoking https://example.org and getting the below error.

FAILED: HWTHCONN connect attempt                                             
Return code: HWTH-COMMUNICATION-ERROR                                        
Service: 001835009                                                           
Reason Code: HWTH-RSN-REDIRECTED                                             
Reason Desc: EDC9501I The name does not resolve for the supplied parameters. 

Request your help in fixing this issue.  

Thanks,
Arun

**Comment by aravind-selvakumar** [comment]
Hello Arunk,

 you could first checking on these parameters,
1. try accessing http://example.org/  (note: protocol is http here) from your implementation, if it works then you are missing configurations essential for https protocol (for example keychain). I've provided essential https configuration here https://medium.com/@aravind.selvakumar/in-place-modernization-z-os-web-enablement-toolkit-6bbd9a8bb67e

2. if http://example.org/ does not work, then try some simple http(not https) endpoints within your organization's network. if this does not work, it essentially means that your network policies need change(talk with you network administrators)

**Comment by arunk-81** [comment]
Hi Aravind,

Thanks for the quick response. We are facing the same issue with http as well.  

We are able to access the link from browser . So I guess it is due to some restriction within zOS. I will check with the infra team regarding this,

Thanks,
Arun

**Comment by aravind-selvakumar** [comment]
> Hi Aravind,
> 
> Thanks for the quick response. We are facing the same issue with http as well.
> 
> We are able to access the link from browser . So I guess it is due to some restriction within zOS. I will check with the infra team regarding this,
> 
> Thanks, Arun

Perfect, could you proceed to close this issue.

**Comment by arunk-81** [comment]
Sure, will close this issue.
